---

version: "3.8"

services:
  flame-app:
    image: pawelmalak/flame
    container_name: con-flame
    ports:
      - '5005:5005'
    volumes:
      - '/opt/flame/data:/app/data'
    environment:
      - 'PASSWORD=1234567'
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: con-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Moscow
    volumes:
      - /opt/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: flamenet
